# runtime: nodejs10

# instance_class: F2

# env_variables:
#   BUCKET_NAME: "example-gcs-bucket"

# handlers:
# - url: /stylesheets
#   static_dir: stylesheets

# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

# [START appengine_websockets_yaml]
runtime: nodejs
env: standard


# Use only a single instance, so that this local-memory-only chat app will work
# consistently with multiple users. To work across multiple instances, an
# extra-instance messaging system or data store would be needed.
manual_scaling:
  instances: 1

network:
  session_affinity: true
# [END appengine_websockets_yaml]